import camel_case_dash from './camel-case-dash';

export default function wp_globals(): Record< string, string | string[] > {
	// See https://github.com/WordPress/WordPress/tree/master/wp-includes/assets
	const packages = [
		'a11y',
		'annotations',
		'api-fetch',
		'autop',
		'blob',
		'block-directory',
		'block-editor',
		'block-library',
		'block-serialization-default-parser',
		'blocks',
		'components',
		'compose',
		'core-data',
		'customize-widgets',
		'data',
		'data-controls',
		'date',
		'deprecated',
		'dom',
		'dom-ready',
		'edit-post',
		'edit-site',
		'edit-widgets',
		'editor',
		'element',
		'escape-html',
		'format-library',
		'hooks',
		'html-entities',
		'i18n',
		'is-shallow-equal',
		'keyboard-shortcuts',
		'keycodes',
		'list-reusable-blocks',
		'media-utils',
		'notices',
		'nux',
		'plugins',
		'preferences',
		'preferences-persistence',
		'primitives',
		'priority-queue',
		'redux-routine',
		'reusable-blocks',
		'rich-text',
		'server-side-render',
		'shortcode',
		'style-engine',
		'token-list',
		'url',
		'viewport',
		'warning',
		'widgets',
		'wordcount',
	];

	const others = {
		'backbone': 'Backbone',
		'jquery': 'jQuery',
		'lodash': 'lodash',
		'moment': 'moment',
		'react': 'React',
		'react-dom': 'ReactDOM',
		'tinymce': 'tinymce',
	};

	return {
		...others,
		...Object.fromEntries(
			packages.map( handle => [ `@wordpress/${ handle }`, `wp.${ camel_case_dash( handle ) }` ] ),
		),
	};
}
